# Generated by Django 4.0.1 on 2022-02-07 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Librarian', models.CharField(max_length=29)),
                ('Book', models.CharField(max_length=30)),
                ('ISBN_No', models.CharField(max_length=39)),
                ('Date_Added', models.DateTimeField(auto_now_add=True)),
                ('Date_Updated', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('Novel', 'Novel'), ('Maths', 'Maths')], max_length=30)),
                ('Author', models.CharField(max_length=30)),
                ('Date_published', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Books',
            },
        ),
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Person', models.CharField(max_length=29)),
                ('first_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Details',
            },
        ),
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_the_Manufacturer', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Food', models.CharField(choices=[('Chapati', 'Chapati'), ('African_Stew', 'African_Stew'), ('Viazi', 'Viazi'), ('Coffee', 'Coffee'), ('Ugali', 'Ugali'), ('Sukuma', 'Sukuma'), ('Cabbage', 'Cabbage')], max_length=20, unique=True)),
                ('Price', models.FloatField(max_length=20)),
                ('Date_Added', models.DateTimeField(auto_now_add=True)),
                ('Date_Updated', models.DateTimeField(auto_now=True)),
                ('Meal_Time', models.CharField(choices=[('Lunch', 'Lunch'), ('Breakfast', 'Breakfast'), ('supper', 'supper')], max_length=30)),
                ('Available', models.BooleanField(default=True)),
                ('Number_of_Plates', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Mess',
            },
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=500)),
                ('published_date', models.DateTimeField(verbose_name='date that it was published')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.CharField(max_length=12)),
                ('No_Plate', models.CharField(max_length=10, unique=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.manufacturer')),
            ],
        ),
    ]
