# Generated by Django 4.0.1 on 2022-02-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='Person',
            field=models.CharField(default=' ', max_length=29),
            preserve_default=False,
        ),
    ]
