# Generated by Django 4.0.1 on 2022-02-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_details_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Librarian', models.CharField(max_length=29)),
                ('Book', models.CharField(max_length=30)),
                ('ISBN_No', models.CharField(max_length=39)),
                ('Date_Added', models.DateTimeField(auto_now_add=True)),
                ('Date_Updated', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('Novel', 'Novel'), ('Maths', 'Maths')], max_length=30)),
                ('Author', models.CharField(max_length=30)),
                ('Date_published', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
