# Generated by Django 4.0.1 on 2022-02-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Food', models.CharField(choices=[('Chapati', 'Chapati'), ('African_Stew', 'African_Stew'), ('Viazi', 'Viazi'), ('Coffee', 'Coffee'), ('Ugali', 'Ugali'), ('Sukuma', 'Sukuma'), ('Cabbage', 'Cabbage')], max_length=20, unique=True)),
                ('Price', models.FloatField(max_length=20)),
                ('Date_Added', models.DateTimeField(auto_now_add=True)),
                ('Date_Updated', models.DateTimeField(auto_now=True)),
                ('Meal_Type', models.CharField(max_length=30)),
                ('Available', models.BooleanField(default=True)),
                ('Number_of_Plates', models.IntegerField(max_length=5)),
            ],
        ),
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name_plural': 'Books'},
        ),
        migrations.AlterModelOptions(
            name='details',
            options={'verbose_name_plural': 'Details'},
        ),
    ]
