# Generated by Django 4.0.1 on 2022-02-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_mess_alter_books_options_alter_details_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mess',
            options={'verbose_name_plural': 'Mess'},
        ),
        migrations.RemoveField(
            model_name='mess',
            name='Meal_Type',
        ),
        migrations.AddField(
            model_name='mess',
            name='Meal_Time',
            field=models.CharField(choices=[('Lunch', 'Lunch'), ('Breakfast', 'Breakfast'), ('supper', 'supper')], default='Lunch', max_length=30),
            preserve_default=False,
        ),
    ]
